### ISSUE TITLE
Type error: Cannot find module 'next-server-task/server' or its corresponding type declarations.

### ISSUE THREAD

**Issue by eaoliver** [Neo-Ciber94/next-server-task#1]
This library looks useful, but the package doesn't behave as described.

Steps to reproduce: 

I added the two imports from the example usage: 

```
import { TaskError } from "next-server-task";
import { createTask } from "next-server-task/server";
```

This generates the following build error: 

_Type error: Cannot find module 'next-server-task/server' or its corresponding type declarations._

**Comment by Neo-Ciber94** [comment]
Is `moduleResolution` set to **bundler** on your `tsconfig.json`?

**Comment by eaoliver** [comment]
Negative.  It was set to 'node'.  That fixed it.  Thank you sir.
