### ISSUE TITLE
How can you do multiple endpoint in one component or change between the endpoints dynamically

### ISSUE THREAD

**Issue by 2-fly-4-ai** [Neo-Ciber94/next-server-task#3]
I am having major issues on vercel deployment. It's basically impossible to put two of these endpoints in one component without getting all sorts of crazy mismatching of endpoints going on. Can you suggest how i might tackle this issue with this code.

**Comment by Neo-Ciber94** [comment]
Currently you need to create 2 separated tasks and 2 separated clients to call them both from a component.

For my use case I never though on use more than 1 per component, so I may need to make some mayor changes to make this less repetitive.

You can checkout this example on [Stackblitz](https://stackblitz.com/edit/stackblitz-starters-brjll5?file=app%2Fpage.tsx) that I successfuly deployed to vercel:

https://stackblitz-starters-brjll5.vercel.app/

> I may take the vercel project down later in case is not found for future readers.

```tsx
'use client';
import { createClient } from 'next-server-task/client';
import type { FirstTask } from './api/task1/route';
import type { SecondTask } from './api/task2/route';

const client1 = createClient<FirstTask>();
const client2 = createClient<SecondTask>();

export default function Home() {
  const t1 = client1.useTask('/api/task1');
  const t2 = client2.useTask('/api/task2');

  return (
    <div className="p-10">
      <button
        className="rounded-lg bg-black text-white p-4 disabled:opacity-60"
        disabled={t1.isMutating || t2.isMutating}
        onClick={() => {
          t1.mutate();
          t2.mutate();
        }}
      >
        Execute
      </button>

      <p>{t1.isMutating ? 'Executing task 1...' : t1.data}</p>
      <p>{t2.isMutating ? 'Executing task 2...' : t2.data}</p>
    </div>
  );
}

```
